torchrun --nnodes=1 \
    --nproc_per_node=1 \
    --master_port=9911 \
    lerobot/scripts/fsdp_train_uni_token.py \
    --policy.type="uni_token" \
    --policy.max_frame=50 \
    --save_freq=2000 \
    --dataset.repo_id="whatever" \
    --dataset.image_transforms.enable=true \
    --dataset.wrist_image_transforms.enable=true \
    --dataset.wrist_image_transforms.is_primary=false \
    --dataset.processor="OpenGVLab/InternVL3_5-1B-HF" \
    --dataset.parent_dir="/mnt/wangxiaofa/robot_dataset/lerobot-format/" \
    --data_mix="simpler_bridge" \
    --dataset.sample_ratio=5 \
    --output_dir="qwen_flow" \
    --batch_size=2 \
    --steps=60_0000 \
    --policy.scheduler_warmup_steps=10000 \
    --policy.scheduler_decay_steps=25000 \
    --policy.scheduler_platform_steps=20000 \
    --policy.optimizer_lr=1e-4 \
    --policy.train_main_layers=0 \
    --policy.freeze_vision_encoder=false \
    --policy.train_expert_only=false \
    --policy.train_from_scratch=true \
    --wandb.project="latent-action" \
    --job_name="0909-latent-action-v0" \
    # --wandb.enable=true \
    